server:
  port: 8082
  max-http-header-size: 1048576
  tomcat:
    max-connections: 3000
    max-http-post-size: 1048576
    max-threads: 1000
spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  typeAliasesPackage: com.gg3083.tb.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.gg3083.tb.mapper : debug
